### ISSUE TITLE
Problema de registro en seguimiento de usuarios

### ISSUE THREAD

**Issue by serviola42** [SmartDataUC/visor-smartdata#17]
El panel de admin no muestra correctamente el número de ingresos por cuenta de usuario al visor de datos. En la pestaña de registros, el número de conexiones por usuario se mantiene fija en 1 para las cuentas admin y usuario. Durante el periodo seleccionado (3 de mayo a 3 de junio) no muestra otras conexiones que se han realizado tanto con la cuenta admin, como con la cuenta de gorecomunicaciones.

**Comment by hsgonzalmu** [comment]
Solcionado, favor de revisar.
