### ISSUE TITLE
Problema para registrar nuevos usuarios

### ISSUE THREAD

**Issue by serviola42** [SmartDataUC/visor-smartdata#18]
El panel de admin presenta problemas al intentar registrar una nueva cuenta de usuario. Al intentar generar una cuenta aparece un mensaje en rojo indicando "Fallo en la actualización del usuario" y la sesión actual termina, volviendo a la pantalla de identificación.

Se han probado diferentes configuraciones, como por ejemplo descartar la opción de administrador, extender la fecha de duración de la cuenta y desactivar el solicitar cambiar contraseña en el primer inicio de sesión.

**Comment by hsgonzalmu** [comment]
Solucionado, intenta cuando puedas hacer pruebas y nos das el ok.
