### ISSUE TITLE
Ajustar visualización de mapa en el apartado de comunas

### ISSUE THREAD

**Issue by serviola42** [SmartDataUC/visor-smartdata#2]
Se requiere ajustar la representación del número de noticias asociadas a la categoría "Santiago" en la visualización de mapa en el apartado de comunas.

El mapa debe contabilizar como "Santiago" aquellas noticias que contengan unicamente la categoría "Santiago", omitiendo las noticias que contengan dos categorías ("Santiago" + Otra comuna de Santiago).

**Comment by jbkunst** [comment]
Iván, hola,

Respecto a este punto. Esperaremos a que la profesora Riva implemente lo presentado en la reunión para identificar noticias de la comuna de santiago?: "como de Santiago", etc?
