### ISSUE TITLE
Ajustar gradiente de visualizaciones de barra y tendencias temporales

### ISSUE THREAD

**Issue by serviola42** [SmartDataUC/visor-smartdata#25]
Se deben ajustar todos los gráficos de barra y tendencias temporales siguiendo el estilo planteado en el figma: https://www.figma.com/design/Qfdd3fNNtpyIEGijzNzvXN/Anal%C3%ADtica-Medios-y-Redes?node-id=4211-2642&t=pQi1OaIZ2PGp4o3z-0

Para el caso de los gráficos de barra asociados a las categorías de noticia se debe utilizar una gradiente de gris a morado, destacando en color morado las tres categorías más relevantes y cambiando el peso de la fuente.

Para el caso de los gráficos de barra de conceptos, se debe utilizar una gradiente de gris a fucsia, destacando en color fucsia los tres conceptos más relevantes y cambiando el peso de la fuente.

Para los gráficos de tendencia histórica (incluyendo el de la herramienta de tendencias), se debe aumentar el grueso del vector, y el tamaño de los títulos que acompañan los ejes.

![image](https://github.com/SmartDataUC/visor-smartdata/assets/29220626/180f8ed0-4280-48ab-9263-c81474ab34ce)

**Comment by jbkunst** [comment]
- [ ] Aumentar grosor lineas.
