### ISSUE TITLE
El visor no está analizando todas los artículos noticiosos

### ISSUE THREAD

**Issue by serviola42** [SmartDataUC/visor-smartdata#9]
El visor no está analizando todas las noticias disponibles en la base de datos de artículos noticiosos.

Las noticias de emol parecen estar cargándose todas sin problemas.

**Comment by jbkunst** [comment]
Hola Iván @serviola42 !

Corregido este punto. Notar que existe una leve diferencia de lo que está en la base de datos que lo que muestra screpos.

Para el día 2024-04-17 el visor y la bbdd muestra 537 items, screpops señala 577 items scrapeados, no necesariamente subidos a la bbdd.
![image](https://github.com/SmartDataUC/visor-smartdata/assets/56481/f294ec19-4899-4800-aede-81ce9238054b)

![image](https://github.com/SmartDataUC/visor-smartdata/assets/56481/d4925c0c-4ca1-48b1-b486-0e02aba7209e)

![image](https://github.com/SmartDataUC/visor-smartdata/assets/56481/5bda8c4c-5870-4aae-83b2-c5a56aa24143)

**Comment by jbkunst** [comment]
@serviola42 

Al revisar este issue tambien noté duplicidad de noticias, por ejemplo:

![image](https://github.com/SmartDataUC/visor-smartdata/assets/56481/dd94343b-2b34-46ec-a9f4-5ed0463f3e20)
 
Creo no tener acceso al repositorio para crear donde corresponde este issue.
